// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    InputBox: typeof import('./src/components/InputBox.vue')['default']
    List: typeof import('./src/components/List.vue')['default']
    ListItem: typeof import('./src/components/ListItem.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    PageWrapper: typeof import('./src/components/PageWrapper.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Test: typeof import('./src/components/Test.vue')['default']
  }
}
